### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by zitsen** [zitsen/unqlite.rs#1]
- Database Engine Handle
  - [ ] unqlite_open
  - [ ] unqlite_config
  - [ ] unqlite_close
- Key/Value Store Interfaces
  - [ ] unqlite_kv_store
  - [ ] unqlite_kv_append
  - [ ] unqlite_kv_store_fmt
  - [ ] unqlite_kv_append_fmt
  - [ ] unqlite_kv_fetch
  - [ ] unqlite_kv_fetch_callback
  - [ ] unqlite_kv_delete
  - [ ] unqlite_kv_config
- Document Store (JSON via Jx9) Interfaces
  - [ ] unqlite_compile
  - [ ] unqlite_compile_file
  - [ ] unqlite_vm_config
  - [ ] unqlite_vm_exec
  - [ ] unqlite_vm_reset
  - [ ] unqlite_vm_release
  - [ ] unqlite_vm_extract_variable
  - [ ] unqlite_vm_dump
- Cursor Iterator Interfaces
  - [ ] unqlite_kv_cursor_init
  - [ ] unqlite_kv_cursor_release
  - [ ] unqlite_kv_cursor_seek
  - [ ] unqlite_kv_cursor_first_entry
  - [ ] unqlite_kv_cursor_last_entry
  - [ ] unqlite_kv_cursor_valid_entry
  - [ ] unqlite_kv_cursor_next_entry
  - [ ] unqlite_kv_cursor_prev_entry
  - [ ] unqlite_kv_cursor_key
  - [ ] unqlite_kv_cursor_key_callback
  - [ ] unqlite_kv_cursor_data
  - [ ] unqlite_kv_cursor_data_callback
  - [ ] unqlite_kv_cursor_delete_entry
  - [ ] unqlite_kv_cursor_reset
- Manual Transaction Manager
  - [ ] unqlite_begin
  - [ ] unqlite_commit
  - [ ] unqlite_rollback
- Utility Interfaces
  - [ ] unqlite_util_load_mmaped_file
  - [ ] unqlite_util_release_mmaped_file
  - [ ] unqlite_util_random_string
  - [ ] unqlite_util_random_num
- In-process Extending Interfaces
  - [ ] unqlite_create_function
  - [ ] unqlite_delete_function
  - [ ] unqlite_create_constant
  - [ ] unqlite_delete_constant
- To be continued
